version: '3'
services:
  backend:
    image: arq-web-backend-img
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    image: arq-web-frontend-img
    ports:
      - "3001:3001"
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./backend/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
