name: Build and Push All Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ github.repository }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6.17.0
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/mern-frontend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6.17.0
        with:
          context: ./backend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/mern-backend:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.17.0
        with:
          context: ./backend/mongo
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/mern-mongodb:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
