name: Build and Push All Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: frontend
            image: sdifrancisco28/mern-frontend
            dockerfile: frontend/Dockerfile
            context: frontend
          - name: backend
            image: sdifrancisco28/mern-backend
            dockerfile: backend/Dockerfile
            context: backend
          - name: mongodb
            image: sdifrancisco28/mern-mongodb
            dockerfile: backend/mongo/Dockerfile
            context: backend/mongo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v6.17.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
